# Generated by Django 5.1.5 on 2025-11-18 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_direccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(editable=False, max_length=20, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=10)),
                ('costo_envio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_final', models.DecimalField(decimal_places=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('CONFIRMADO', 'Confirmado / En Preparación'), ('PICKING', 'Picking de Productos'), ('EMBALAJE', 'En Embalaje'), ('DESPACHO', 'Despachado al Courier'), ('ENTREGADO', 'Entregado al Cliente'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('direccion_envio', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('talla_color', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('variante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.variante')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_orden', to='core.orden')),
            ],
        ),
    ]
