# Generated by Django 5.2.8 on 2025-11-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orden_itemorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='rut',
            field=models.CharField(default='', max_length=12, verbose_name='RUT del Receptor'),
            preserve_default=False,
        ),
    ]
