# Generated by Django 5.2.8 on 2025-11-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_direccion_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='email',
            field=models.EmailField(default='default@correo.com', max_length=254, verbose_name='Email de Contacto'),
            preserve_default=False,
        ),
    ]
