# Generated by Django 5.2.8 on 2025-11-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orden_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tracking ID'),
        ),
    ]
