# Generated by Django 6.0 on 2025-12-04 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orden_codigo_seguimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('hombre', 'Hombres'), ('mujer', 'Mujeres'), ('accesorios', 'Accesorios')], default='unisex', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(choices=[('guess', 'Guess'), ('northface', 'The North Face'), ('ck', 'Calvin Klein'), ('ea7', 'EA7 Armani'), ('coach', 'Coach'), ('mk', 'Michael Kors'), ('ae', 'American Eagle'), ('versace', 'Versace'), ('tommy', 'Tommy Hilfiger')], default='generico', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='RegistroTryOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probador_logs', to='core.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
